### ISSUE TITLE
[not an issue] Simple questions

### ISSUE THREAD

**Issue by EstherMoellman** [bjornstar/intercept-redirect#20]
Hi @bjornstar , thank you for InterceptRedirect.

For long time, the two classical url cleaners have been [SkipRedirect](https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/) and [NeatUrl](https://addons.mozilla.org/en-US/firefox/addon/neat-url/).
I'm not an expert, so please, allow me few simple questions:

1) Can I replace these two add-ons with your InterceptRedirect?
I'm always focused on browser performance. So for me, the less add-ons the better. If your add-on has the same functions, then I would like to replace my current 2 add-ons with yours. And that's the reason of my first question.

2) If the answer to my first question is: "You can replace both add-ons with InterceptRedirect", then what about your script? Do you believe InterceptRedirect script is faster or better than SkipRedirect and NeatUrl?

Thanks in advance.

**Comment by bjornstar** [comment]
Intercept Redirect serves a similar function to SkipRedirect. It doesn't provide any of the functionality of NeatUrl, so it wouldn't be able to replace that.

My goal with Intercept Redirect is to skip specific, known redirects and not attempt to resolve all redirects in all URLs. There is no configuration for Intercept Redirect and it doesn't handle every URL  sent by your browser. It only handles some URLs on the list of supported domains and is more performant and consumes fewer resources.

The key for me is that Intercept Redirect does not request permission to access all hosts, it only requests specific hosts and most of those are dedicated hosts for redirect services (ie. slack-redir.net, t.umblr.com, l.instagram.com). I feel much better running an extension dedicated to this rather than one that runs on my bank's site.

**Comment by EstherMoellman** [comment]
@bjornstar , thanks for your replay.
Understood! The main differentiation of your add-on is PRIVACY.
If you allow me a suggestion, perhaps it'll be nice to mention your explanation at AMO' page, so non-expert users (like me) will know the strengths (PRIVACY) of your add-on. This argument is very solid: "I feel much better running an extension dedicated to this rather than one that runs on my bank's site."

Now, please correct me if I'm wrong: If your add-on only runs at selected domains, from my ignorance I suppose this also is good for browser performance. Am I right? In simple words, SypeRedirect will run at every webpage, thus will consume more RAM, CPU etc. In the other hand, your add-on only will run at specific domains, so less RAM, CPU etc when compared to similar add-ons having full permissions.
In this context, may I say your add-on also is better in PERFORMANCE?

And what about NeatUrl' function? Any chance to add to your add-on this "strip-url" function, so users (like me) focused on browser performance can have less add-ons and more browser performance with your add-on?

I've no idea if the list of tracking-domains covered by your add-on is enough, or if it is a small list of tracking-domains. But I'm against those add-ons covering millions of domains... this is useless and hurts browser performance. The ideal is to have an average global list of tracking-domains covered by your add-on. IMO, if your add-on covers the most important global tracking-domains, then it will be enough.
If your add-on can do that, and also if can include NeatUrl' function... it will be great!

Thank you!

PS: Please, feel free to close this issue.

**Comment by bjornstar** [comment]
Thanks for the feedback, there is definitely room for improvement in the description. Unfortunately, I don't have much energy to work on that when Google is constantly rejecting my extension updates and refusing to tell me why in a clear, concise manner.

As far as the functionality of NeatUrl goes, it doesn't really belong in a redirect skipping extension. It also would require handling every URL request which goes against my principle of only targeting redirect services.

I'll leave this open as a reminder to update the description.
